=== mmnessim/SharpTheoryRazorPages/SharpTheory/Data/data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "description": {
      "properties": {
        "author": { "type": "string" },
        "description": { "type": "string" },
        "title": { "type": "string" },
        "version": { "type": "string" }
      },
      "required": [ "title", "version", "author", "description" ],
      "type": "object"
    },
    "integers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "integer": { "type": "integer" },
          "names": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": [ "integer", "names" ]
      }
    },
    "keys": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "mode": { "type": "string" },
          "integer": { "type": "integer" },
          "sharps": {
            "type": "array",
            "items": { "type": "string" }
          },
          "flats": {
            "type": "array",
            "items": { "type": "string" }
          },
          "num_sharps": { "type": "integer" },
          "num_flats": { "type": "integer" },
          "relative": { "type": "string" },
          "enharmonic": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": [ "name", "mode", "integer", "sharps", "flats", "num_sharps", "num_flats", "relative" ]
      }
    },
    "scales": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "tonic": { "type": "string" },
          "integer": { "type": "integer" },
          "major": {
            "type": "object",
            "properties": {
              "notes": {
                "type": "array",
                "items": { "type": "string" }
              },
              "integers": {
                "type": "array",
                "items": { "type": "integer" }
              }
            },
            "required": [ "notes", "integers" ]
          },
          "natural_minor": {
            "type": "object",
            "properties": {
              "notes": {
                "type": "array",
                "items": { "type": "string" }
              },
              "integers": {
                "type": "array",
                "items": { "type": "integer" }
              }
            },
            "required": [ "notes", "integers" ]
          },
          "harmonic_minor": {
            "type": "object",
            "properties": {
              "notes": {
                "type": "array",
                "items": { "type": "string" }
              },
              "integers": {
                "type": "array",
                "items": { "type": "integer" }
              }
            },
            "required": [ "notes", "integers" ]
          }
        },
        "required": [ "tonic", "integer" ]
      }
    },
    "intervals": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "abbreviation": { "type": "string" },
          "semitones": { "type": "integer" }
        },
        "required": [ "name", "abbreviation", "semitones" ]
      }
    },
    "nondiatonic_scales": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "integers": {
            "type": "array",
            "items": { "type": "integer" }
          }
        },
        "required": [ "name", "integers" ]
      }
    }
  },
  "required": [ "description", "integers", "keys", "scales", "intervals", "nondiatonic_scales" ],
  "title": "Sharp Theory Data",
  "type": "object"
}

=== mmnessim/SharpTheoryRazorPages/SharpTheory/Data/data.json
{
  "description": {
    "title": "SharpTheory",
    "version": "0.0.1",
    "author": "Mounir Nessim",
    "description": "A music theory API and demo site written in C#"
  },
  "integers": [
    {
      "integer": 0,
      "names": [ "C" ]
    },
    {
      "integer": 1,
      "names": [ "C#", "Db" ]
    },
    {
      "integer": 2,
      "names": [ "D" ]
    },
    {
      "integer": 3,
      "names": [ "D#", "Eb" ]
    },
    {
      "integer": 4,
      "names": [ "E", "Fb" ]
    },
    {
      "integer": 5,
      "names": [ "F", "E#" ]
    },
    {
      "integer": 6,
      "names": [ "F#", "Gb" ]
    },
    {
      "integer": 7,
      "names": [ "G" ]
    },
    {
      "integer": 8,
      "names": [ "G#", "Ab" ]
    },
    {
      "integer": 9,
      "names": [ "A" ]
    },
    {
      "integer": 10,
      "names": [ "A#", "Bb" ]
    },
    {
      "integer": 11,
      "names": [ "B", "Cb" ]
    }
  ],
  "keys": [
    {
      "name": "C Major",
      "mode": "major",
      "integer": 0,
      "sharps": [],
      "flats": [],
      "num_sharps": 0,
      "num_flats": 0,
      "relative": "A minor"
    },
    {
      "name": "G Major",
      "mode": "major",
      "integer": 7,
      "sharps": [ "F#" ],
      "flats": [],
      "num_sharps": 1,
      "num_flats": 0,
      "relative": "E minor"
    },
    {
      "name": "D Major",
      "mode": "major",
      "integer": 2,
      "sharps": [ "F#", "C#" ],
      "flats": [],
      "num_sharps": 2,
      "num_flats": 0,
      "relative": "B minor"
    },
    {
      "name": "A Major",
      "mode": "major",
      "integer": 9,
      "sharps": [ "F#", "C#", "G#" ],
      "flats": [],
      "num_sharps": 3,
      "num_flats": 0,
      "relative": "F# minor"
    },
    {
      "name": "E Major",
      "mode": "major",
      "integer": 4,
      "sharps": [ "F#", "C#", "G#", "D#" ],
      "flats": [],
      "num_sharps": 4,
      "num_flats": 0,
      "relative": "C# minor"
    },
    {
      "name": "B Major",
      "mode": "major",
      "integer": 11,
      "sharps": [ "F#", "C#", "G#", "D#", "A#" ],
      "flats": [],
      "num_sharps": 5,
      "num_flats": 0,
      "relative": "G# minor",
      "enharmonic": [ "Cb Major", "A# minor" ]
    },
    {
      "name": "F# Major",
      "mode": "major",
      "integer": 6,
      "sharps": [ "F#", "C#", "G#", "D#", "A#", "E#" ],
      "flats": [],
      "num_sharps": 6,
      "num_flats": 0,
      "relative": "D# minor",
      "enharmonic": [ "Gb Major", "Eb minor" ]
    },
    {
      "name": "C# Major",
      "mode": "major",
      "integer": 1,
      "sharps": [ "F#", "C#", "G#", "D#", "A#", "E#", "B#" ],
      "flats": [],
      "num_sharps": 7,
      "num_flats": 0,
      "relative": "A# minor",
      "enharmonic": [ "Db Major", "Bb minor" ]
    },
    {
      "name": "F Major",
      "mode": "major",
      "integer": 5,
      "sharps": [],
      "flats": [ "Bb" ],
      "num_sharps": 0,
      "num_flats": 1,
      "relative": "D minor"
    },
    {
      "name": "Bb Major",
      "mode": "major",
      "integer": 10,
      "sharps": [],
      "flats": [ "Bb", "Eb" ],
      "num_sharps": 0,
      "num_flats": 2,
      "relative": "G minor"
    },
    {
      "name": "Eb Major",
      "mode": "major",
      "integer": 3,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab" ],
      "num_sharps": 0,
      "num_flats": 3,
      "relative": "C minor"
    },
    {
      "name": "Ab Major",
      "mode": "major",
      "integer": 8,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db" ],
      "num_sharps": 0,
      "num_flats": 4,
      "relative": "F minor"
    },
    {
      "name": "Db Major",
      "mode": "major",
      "integer": 1,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db", "Gb" ],
      "num_sharps": 0,
      "num_flats": 5,
      "relative": "Bb minor",
      "enharmonic": [ "C# Major", "A# minor" ]
    },
    {
      "name": "Gb Major",
      "mode": "major",
      "integer": 6,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db", "Gb", "Cb" ],
      "num_sharps": 0,
      "num_flats": 6,
      "relative": "Eb minor",
      "enharmonic": [ "F# Major", "D# minor" ]
    },
    {
      "name": "Cb Major",
      "mode": "major",
      "integer": 11,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db", "Gb", "Cb", "Fb" ],
      "num_sharps": 0,
      "num_flats": 7,
      "relative": "Ab minor",
      "enharmonic": [ "B Major", "F# minor" ]
    },
    {
      "name": "A minor",
      "mode": "minor",
      "integer": 9,
      "sharps": [],
      "flats": [],
      "num_sharps": 0,
      "num_flats": 0,
      "relative": "C Major"
    },
    {
      "name": "E minor",
      "mode": "minor",
      "integer": 4,
      "sharps": [ "F#" ],
      "flats": [],
      "num_sharps": 1,
      "num_flats": 0,
      "relative": "G Major"
    },
    {
      "name": "B minor",
      "mode": "minor",
      "integer": 11,
      "sharps": [ "F#", "C#" ],
      "flats": [],
      "num_sharps": 2,
      "num_flats": 0,
      "relative": "D Major"
    },
    {
      "name": "F# minor",
      "mode": "minor",
      "integer": 6,
      "sharps": [ "F#", "C#", "G#" ],
      "flats": [],
      "num_sharps": 3,
      "num_flats": 0,
      "relative": "A Major"
    },
    {
      "name": "C# minor",
      "mode": "minor",
      "integer": 1,
      "sharps": [ "F#", "C#", "G#", "D#" ],
      "flats": [],
      "num_sharps": 4,
      "num_flats": 0,
      "relative": "E Major"
    },
    {
      "name": "G# minor",
      "mode": "minor",
      "integer": 8,
      "sharps": [ "F#", "C#", "G#", "D#", "A#" ],
      "flats": [],
      "num_sharps": 5,
      "num_flats": 0,
      "relative": "B Major",
      "enharmonic": [ "Ab minor", "Cb Major" ]
    },
    {
      "name": "D# minor",
      "mode": "minor",
      "integer": 3,
      "sharps": [ "F#", "C#", "G#", "D#", "A#", "E#" ],
      "flats": [],
      "num_sharps": 6,
      "num_flats": 0,
      "relative": "F# Major",
      "enharmonic": [ "Eb minor", "Gb Major" ]
    },
    {
      "name": "A# minor",
      "mode": "minor",
      "integer": 10,
      "sharps": [ "F#", "C#", "G#", "D#", "A#", "E#", "B#" ],
      "flats": [],
      "num_sharps": 7,
      "num_flats": 0,
      "relative": "C# Major",
      "enharmonic": [ "Bb minor", "Db Major" ]
    },
    {
      "name": "D minor",
      "mode": "minor",
      "integer": 2,
      "sharps": [],
      "flats": [ "Bb" ],
      "num_sharps": 0,
      "num_flats": 1,
      "relative": "F Major"
    },
    {
      "name": "G minor",
      "mode": "minor",
      "integer": 7,
      "sharps": [],
      "flats": [ "Bb", "Eb" ],
      "num_sharps": 0,
      "num_flats": 2,
      "relative": "Bb Major"
    },
    {
      "name": "C minor",
      "mode": "minor",
      "integer": 0,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab" ],
      "num_sharps": 0,
      "num_flats": 3,
      "relative": "Eb Major"
    },
    {
      "name": "F minor",
      "mode": "minor",
      "integer": 5,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db" ],
      "num_sharps": 0,
      "num_flats": 4,
      "relative": "Ab Major"
    },
    {
      "name": "Bb minor",
      "mode": "minor",
      "integer": 10,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db", "Gb" ],
      "num_sharps": 0,
      "num_flats": 5,
      "relative": "Db Major",
      "enharmonic": [ "A# minor", "C# Major" ]
    },
    {
      "name": "Eb minor",
      "mode": "minor",
      "integer": 3,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db", "Gb", "Cb" ],
      "num_sharps": 0,
      "num_flats": 6,
      "relative": "Gb Major",
      "enharmonic": [ "D# minor", "F# Major" ]
    },
    {
      "name": "Ab minor",
      "mode": "minor",
      "integer": 8,
      "sharps": [],
      "flats": [ "Bb", "Eb", "Ab", "Db", "Gb", "Cb", "Fb" ],
      "num_sharps": 0,
      "num_flats": 7,
      "relative": "Cb Major",
      "enharmonic": [ "G# minor", "B Major" ]
    }
  ],
  "scales": [
    {
      "tonic": "C",
      "integer": 0,
      "major": {
        "notes": [ "C", "D", "E", "F", "G", "A", "B" ],
        "integers": [ 0, 2, 4, 5, 7, 9, 11 ]
      },
      "natural_minor": {
        "notes": [ "C", "D", "Eb", "F", "G", "Ab", "Bb" ],
        "integers": [ 0, 2, 3, 5, 7, 8, 10 ]
      },
      "harmonic_minor": {
        "notes": [ "C", "D", "Eb", "F", "G", "Ab", "B" ],
        "integers": [ 0, 2, 3, 5, 7, 8, 11 ]
      }
    },
    {
      "tonic": "C#",
      "integer": 1,
      "major": {
        "notes": [ "C#", "D#", "E#", "F#", "G#", "A#", "B#" ],
        "integers": [ 1, 3, 5, 6, 8, 10, 0 ]
      },
      "natural_minor": {
        "notes": [ "C#", "D#", "E", "F#", "G#", "A", "B" ],
        "integers": [ 1, 3, 4, 6, 8, 9, 11 ]
      },
      "harmonic_minor": {
        "notes": [ "C#", "D#", "E", "F#", "G#", "A", "B#" ],
        "integers": [ 1, 3, 4, 6, 8, 9, 0 ]
      }
    },
    {
      "tonic": "Db",
      "integer": 1,
      "major": {
        "notes": [ "Db", "Eb", "F", "Gb", "Ab", "Bb", "C" ],
        "integers": [ 1, 3, 5, 6, 8, 10, 0 ]
      }
    },
    {
      "tonic": "D",
      "integer": 2,
      "major": {
        "notes": [ "D", "E", "F#", "G", "A", "B", "C#" ],
        "integers": [ 2, 4, 6, 7, 9, 11, 1 ]
      },
      "natural_minor": {
        "notes": [ "D", "E", "F", "G", "A", "Bb", "C" ],
        "integers": [ 2, 4, 5, 7, 9, 10, 0 ]
      },
      "harmonic_minor": {
        "notes": [ "D", "E", "F", "G", "A", "Bb", "C#" ],
        "integers": [ 2, 4, 5, 7, 9, 10, 1 ]
      }
    },
    {
      "tonic": "D#",
      "integer": 3,
      "natural_minor": {
        "notes": [ "D#", "E#", "F#", "G#", "A#", "B", "C#" ],
        "integers": [ 3, 5, 6, 8, 10, 11, 1 ]
      },
      "harmonic_minor": {
        "notes": [ "D#", "E#", "F#", "G#", "A#", "B", "C##" ],
        "integers": [ 3, 5, 6, 8, 10, 11, 2 ]
      }
    },
    {
      "tonic": "Eb",
      "integer": 3,
      "major": {
